[[ldid]]
arch = "aarch64"
git-tree-sha1 = "710ccf31f51cc296c408783cae1e1e9fcab5354e"
os = "macos"

    [[ldid.download]]
    sha256 = "db020a5e6c29147345ade316b8e007a160a79213bfbc171b338f88b27b33b873"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.aarch64-apple-darwin.tar.gz"
[[ldid]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08168644a9a868f471bce6a38c87a03c8f4838a4"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "87f6ff3d8f8c26eaa8154cf5e794177e4c95689131c1ba778c02fb5b2138a23e"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.aarch64-linux-gnu-cxx03.tar.gz"
[[ldid]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8af9ca9b0fc6077dcd279ecc46417c4db88513c"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "0a3653a0dc74d175e971492d7600a7a30e37545dbf0d19dec6c4ddf8739b6c1e"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.aarch64-linux-gnu-cxx11.tar.gz"
[[ldid]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5024a4860ed3b519cf25c2abe3d17ca8b88cf54"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "6f6789311386865a46432b865f80055b3d13a81eca44e8c3ce94250fdf4913cc"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.aarch64-linux-musl-cxx03.tar.gz"
[[ldid]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeceb4553ec3ad1f58112d4d5246d0e67491828e"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "689eecde81a1edc40a15beea46844c537d9d2f1038294618cb6f1dd605037643"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.aarch64-linux-musl-cxx11.tar.gz"
[[ldid]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67e5e89d27184291ef59b59c8efc33c91560d0e4"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "1f6d1ba2e0f2ed6fa60a7f764ed7ca6f4f707780ec9c0e1f8f06a811308e611b"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ldid]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "021ac658c3c58359caf162950c6c9fed870e665e"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "69d4e401297d24fc964fbe9280f7788173945b6587ddd9b3ea0fe8fb2298a0b1"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ldid]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f23ff44260df71070f2b0bbb798b4e22aa73062"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "db6fa10f0f302620bd066ec5d3d75fdda0a14a70e46c47d35988c600e758a056"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ldid]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1184e45d50fa53b54122dda8e163b7a807e5baca"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "ad667c42de2f206591fe513d78936fdfed8ea56e24894daca4b08ee1d9c230a2"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ldid]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c331beecb1e4a1eaff58edf4ad15980335e7cae"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "f3928234c63342ad8e190eb5f4ad71e3d6ddf26b085a1a7c70185f61be1c8b86"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ldid]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afcd1aea9b1c5729e1b98a659d9012b58cd17fa3"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "d7b4cea4f911b99598c08fa6fc0ce3e326c7498d2a65b8f410286fd110159553"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ldid]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fdc785059bb845dc006fb08551ba66ac2b36272"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "6b726e3fefc6cf58af12041caea969930b958404f573d7f05347d11ae5c9a8c7"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ldid]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cbd33abf9f4278a165de34632e6c43c0a23c43f"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "f33ea4ae6124c094d2e0e3dbc8d1d62af43b03ef537b2ff755250bf288a88a7d"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ldid]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ff977db88652efed1b139458a21198ee7c4542f"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "93771c6eb8b1142a324e28444f6072f036f55a5362a84b504a94b9bf3a162ded"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.i686-linux-gnu-cxx03.tar.gz"
[[ldid]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a792bceecfda6c5f526abbe66e18b38b3267849f"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "1c03a8af188762afe88ab672885fda7e3a0a8d65e6633051da9d743415eed0e9"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.i686-linux-gnu-cxx11.tar.gz"
[[ldid]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dbef2084fe939dba600c6fc9bdc4cb3996c877a"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "8071922d9110ad1e57138166371c3383cb8fd227ce20c58f4680940dda41030a"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.i686-linux-musl-cxx03.tar.gz"
[[ldid]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afff494ff581992647b7816cf7791fd50dbef33e"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "419a66b80b708e671d3b535533ed6198aa91eff3e1ee81e7ed3f666455476245"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.i686-linux-musl-cxx11.tar.gz"
[[ldid]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78343b9862a073d729b5da1aa97539ac8b3af6f3"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "725160029cc164ae831d9dc73b37109ec8cae322d715b62d373d20ecece90a09"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ldid]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ddbf76538669f7ab41f20e025036c432703bb6f"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "a79870dee2e7a861809753e8aa8112db65cf14e8ce3a1731a511a94412421681"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ldid]]
arch = "x86_64"
git-tree-sha1 = "42dea398f56cbcf529b25de87a92b8e94841f6a6"
os = "macos"

    [[ldid.download]]
    sha256 = "bff714b9ff321a3f200e79228555f646ef08606286d14bb086b0313f3448dbbd"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-apple-darwin.tar.gz"
[[ldid]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3dce1465f3b05af8504e1cd86ac3feeee011ced0"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "61c3fd7f5bcf68094c7f4ee702605b3d4e3e947c0a668483a4ef100f388c4d32"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-linux-gnu-cxx03.tar.gz"
[[ldid]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6e699c160089ec25dba63b34b9d25fef4e42097"
libc = "glibc"
os = "linux"

    [[ldid.download]]
    sha256 = "fb2c90cf302e575a983ab811a9c9eb902703651875d2689f3587b6678d1a8c8c"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-linux-gnu-cxx11.tar.gz"
[[ldid]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44458993bd2626237110f43ae5c13d3ea252e63d"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "202efb4ca335157570c7cbec7b0864a5e4498954bea4f3fd72fb3ca79cf91528"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-linux-musl-cxx03.tar.gz"
[[ldid]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cdac9012c97ab71f0a81db7fb04dbaa70f4945f"
libc = "musl"
os = "linux"

    [[ldid.download]]
    sha256 = "d37c2a8f5bfb75c6a4b9fafb97160c8065e1281b9fe85ac51557fe490edad142"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-linux-musl-cxx11.tar.gz"
[[ldid]]
arch = "x86_64"
git-tree-sha1 = "df79f780af836c12473908e3cf86705517287731"
os = "freebsd"

    [[ldid.download]]
    sha256 = "fd846f7949c69053d45a81d38f57d261ec69e724ca9ac74cef20a33fb9c27bcd"
    url = "https://github.com/JuliaBinaryWrappers/ldid_jll.jl/releases/download/ldid-v2.1.3+0/ldid.v2.1.3.x86_64-unknown-freebsd.tar.gz"
